# Generated by Django 3.2.13 on 2022-08-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('DOB', models.DateField()),
                ('AGE', models.IntegerField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('mail', models.EmailField(max_length=250)),
                ('adress', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=100)),
            ],
        ),
    ]
